services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: gachamelia
      POSTGRES_DB: gachamelia
    ports:
      - "5433:5432"
    volumes:
      - postgres_gachamelia_data:/var/lib/postgresql/data

volumes:
  postgres_gachamelia_data: